name: Tag push
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print data
        run: echo "GITHUB_SHA=${GITHUB_SHA}   GITHUB_REF=${GITHUB_REF}   TAG_NAME=$(git describe $GITHUB_SHA --tags)"
